apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rp
  labels:
    app: go-rp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-rp
  template:
    metadata:
      labels:
        app: go-rp
    spec:
      containers:
      - name: go-rp
        image: gcr.io/pivotal-knative/asu/go-rp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-rp
spec:
  type: LoadBalancer
  selector:
    app: go-rp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
